### ISSUE TITLE
Dev vs Prod publishing

### ISSUE THREAD

**Issue by FeMaffezzolli** [swellstores/community#104]
I'm facing the same problem, my dev environment is getting updated when I "publish updates" from the storefront editor, but not the production one.
On the editor I see "Origin V.2.0.10".

_Originally posted by @FeMaffezzolli in https://github.com/swellstores/community/discussions/77#discussioncomment-4755968_

**Comment by logeshswell** [comment]
@FeMaffezzolli The publishing issue is fixed in your storefront now and also updated in the linked discussion thread. 
So, I am closing this issue now.
Please feel free to reopen this issue if it's not working fine as expected.
