### ISSUE TITLE
Creating draft order via API

### ISSUE THREAD

**Issue by jdevries14** [swellstores/community#217]
Hi,

Please let me know if I created this issue in the wrong place.

Since there is no possibility within Swell for quotations we were thinking of using the `draft` orders as quotations. Is there a way to create draft orders via the backend PHP API? Because passing a `status` is not possible, since `status` is a read-only field.

Thanks in advance! :_)

**Comment by ericingram** [comment]
A draft order is actually a `/carts` record with `draft: true`. Here's how to create one with the backend API:

What kind of quotations are you looking to create?
